spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codercommunity
    username: root
    password: .lht@19961025.
  flyway:
    enabled: true
    baseline-on-migrate: true  # 数据库不是空，需要设置为true
    clean-disabled: true # 禁止清理数据表
    locations: classpath:db/migration
    baseline-version: 1

github:
  client:
    redirect-url: http://localhost:8080/callback
    id: 2c51895939179fdfd18c
    secret: a1aca8b1b2ee7df986d5d58ae500c6412af52c19
    access-token-url: https://github.com/login/oauth/access_token
    user-info-url: https://api.github.com/user


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:      # 日志记录位置
    name: logs/coderCommunity.log
  level:      # 日志级别
    root: info
#    cug:
#      cs:
#        codercommunity:
#          mapper: debug  # 可以为不同的模块定义不同的日志级别
  logback:
    rollingpolicy:
      max-file-size: 200MB   # 日志最大文件大小
      max-history: 30       # 日志记录的最大天数