spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codercommunity
    username: root
    password: .lht@19961025.
  flyway:
    enabled: true
    baseline-on-migrate: true  # 数据库不是空，需要设置为true
    clean-disabled: true # 禁止清理数据表
    locations: classpath:db/migration
    baseline-version: 1
github:
  client:
    redirecturl: http://localhost:8080/callback
    id: 2c51895939179fdfd18c
    secret: bccdf43047598e2c7f67259ca87d4c05d728a538
